name: "ST-CAFFEINE"

on:
  schedule:
    - cron: "45 6 * * *"  # testing cron expression

jobs:
  build: 
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v3"
        with:
          persist-credentials: false

      - name: "Setting up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: "Running python script (workflow_logger.py)"
        run: python workflow_logger.py

      - name: "Commiting empty changes"
        run: |
          git config --global user.name "${{secrets.USER_NAME}}"
          git config --global user.email "${{secrets.USER_EMAIL}}"
          git config --global user.passwd "${{secrets.USER_PASSWD}}"

          git add .
          git commit --allow-empty -m "workflow logs updated"

      - name: "Pushing empty commit"
        uses: "ad-m/github-push-action@master"
        with: 
          github_token: ${{secrets.TOKEN}}
